version: '3.8'

services:

  postgis_db_data:
    build: ./db_data
    container_name: postgis_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports:
      - "8888:5432"

  postgis_db_gestion:
    build: ./db_gestion
    container_name: postgis_gestion
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion
    ports:
      - "9999:5432"

